language: python
cache: pip
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r test-requirements.txt -U
services:
  - redis-server
script:
  - flake8 cachext
  - pytest tests
after_success:
  - CODECLIMATE_REPO_TOKEN=dd64ed5469f00b8a31a5064a7f1cde06968bf7bdc3b2735cb8ad4eb33b88c7a9 codeclimate-test-reporter
  - coveralls
